language: node_js
script: make lint
node_js: 10

deploy:
  - provider: script
    script: make release-ship release-appliance
    on:
      repo: replicatedhq/replicated-starter-ship
      branch: master
