apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-bundle
  labels:
    app: example
    component: support-bundle
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: support-bundle
  template:
    metadata:
      labels:
        tier: support-bundle
    spec:
      containers:
      - name: support-bundle
        image: replicated/support-bundle
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - sleep infinity



